# Generated by Django 5.2.12 on 2026-03-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combos', '0001_initial'),
        ('menu_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='menu_items',
            field=models.ManyToManyField(related_name='combos', to='menu_items.menuitem'),
        ),
    ]
