# Generated by Django 5.2.12 on 2026-03-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combos', '0002_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['restaurant'], name='combo_restaur_217f64_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['is_available'], name='combo_is_avai_e2e13d_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['-average_rating'], name='combo_average_8ef9f0_idx'),
        ),
    ]
