# Generated by Django 5.2.12 on 2026-03-04 18:56

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('entree', 'Entree'), ('side', 'Side'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('calories', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingredients', models.TextField(blank=True)),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'menu_item',
                'ordering': ['restaurant', 'name'],
                'indexes': [models.Index(fields=['restaurant'], name='menu_item_restaur_2b3c73_idx'), models.Index(fields=['category'], name='menu_item_categor_a72ffc_idx'), models.Index(fields=['in_stock'], name='menu_item_in_stoc_15cf95_idx'), models.Index(fields=['-average_rating'], name='menu_item_average_2423c2_idx')],
            },
        ),
    ]
